### ISSUE TITLE
TypeError: bind_simulation_device() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by Yanbing-Ciel** [FedML-AI/doc.fedml.ai#165]
Dear FedML Development Team,

Thank you for providing such an incredible framework for federated learning. 

I recently encountered an issue when running the example in the FedMl Documentation. The error suggests that the bind_simulation_device() function was called with three arguments, while its definition only accepts two.

Here is the detailed traceback:

Traceback (most recent call last):
  File "C:\Users\yangy\PycharmProjects\pythonProject4\test.py", line 6, in <module>
    fedml.run_simulation()
  File "C:\Users\yangy\.conda\envs\fedml_env\lib\site-packages\fedml\launch_simulation.py", line 16, in run_simulation
    args = fedml.init()
  File "C:\Users\yangy\.conda\envs\fedml_env\lib\site-packages\fedml\__init__.py", line 160, in init
    mlops.init(args, should_init_logs=should_init_logs)
  File "C:\Users\yangy\.conda\envs\fedml_env\lib\site-packages\fedml\mlops\__init__.py", line 15, in init
    mlops.init(args, should_init_logs=should_init_logs)
  File "C:\Users\yangy\.conda\envs\fedml_env\lib\site-packages\fedml\core\mlops\__init__.py", line 131, in init
    MLOpsStore.mlops_bind_result = bind_simulation_device(args, api_key, args.config_version)
TypeError: bind_simulation_device() takes 2 positional arguments but 3 were given

**Comment by wuxiaozhi123456** [comment]
您解决了吗
